### ISSUE TITLE
arrows from grid wrong  direction

### ISSUE THREAD

**Issue by prspyder** [DanteWinters/lux-power-distribution-card#63]
Hi so I dont know if by default is like this but if I'm exporting power to the grid arrows should be pointed at the other direction and it seems mine is working backwards.  

![exporting 2](https://github.com/user-attachments/assets/c6d626ae-8884-46b3-a741-a97e03662f71)
![exporting](https://github.com/user-attachments/assets/8480a4d2-cbba-4d4e-8bdb-9a5cee9239d0)

**Comment by danielraffel** [comment]
I haven't experienced this since I am not exporting power yet (tho it does occasionally seem to push tiny amounts and the arrows appear to be correct.) For the sake of others who might stumble on this issue can you share the helper and anything else you had to do? I presume the configuration.yaml change might be something like:

```
template:
  - sensor:
      - name: "Inverted Grid Power"
        state: >
          {{ states('sensor.grid_power') | float * -1 }}
        unit_of_measurement: "W"
        unique_id: "inverted_grid_power"
        icon: "mdi:power-plug-off"
```

**Comment by DanteWinters** [comment]
Hi @prspyder 
Based on the name of the entity you have (Deye/SunSync/Sol-Ark Grid power), I'm going to assume you aren't using this card with a LuxPower inverter? The arrows are fine for the LuxPower integration. I think the integrations just have it differently. Nevertheless, I added an optional config you can add to your card to reverse the grid flow card.
```yaml
grid_flow:
  entities:
    - sensor.your_entity
  reverse: true
```
This should fix it without needing to use a template. Implementing it on my system shows the desired result
