### ISSUE TITLE
Error when updating from 1.5.1 to 1.6.1

### ISSUE THREAD

**Issue by danielraffel** [DanteWinters/lux-power-distribution-card#70]
**Update:** [found this comment](https://github.com/DanteWinters/lux-power-distribution-card/issues/57#issuecomment-2267123872) which alluded to the update needing the cache to be flushed in the browser. Yep! That fixed this. Can also confirm sensor.dongle_40_4c_XX_XX_XX_XX_tinner works.

When upgrading from version 1.5.1 to 1.6.1, I encounter an error in Home Assistant: `undefined is not an object (evaluating 'this._config.temp.is_used')`. As a result, the card no longer loads. However, downgrading back to 1.5.1 restores functionality when using the code below and the card loads correctly. Note: I am using a [3rd party dongle with EG4](https://danielraffel.me/2024/10/28/how-i-built-a-real-time-solar-dashboard-for-my-eg4-18kpv-inverter-using-home-assistant/).

```
      - type: custom:lux-power-distribution-card
        inverter_count: 1
        battery_soc:
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_soc
        battery_flow:
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_batteryflow_live
        home_consumption:
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_pload
        grid_flow:
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_gridflow_live
        pv_power:
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_pall
          show_individual: false
        battery_voltage:
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_vbat
        update_time:
          entities:
            - sensor.last_bank_update_formatted
          show_last_update: true
        grid_indicator:
          hue: true
        status_codes:
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_warningcode
          no_grid_is_warning: true
        refresh_button: right
```

BTW, I also tried adding the following internal temperature reading [as suggested in this comment](https://github.com/DanteWinters/lux-power-distribution-card/issues/43#issuecomment-2648792247), but the same error persisted regardless of whether:
a) is_used was set to true,
b) is_used was set to false,
c) is_used was omitted, or
d) the temp setting was excluded entirely.

I had to downgrade to 1.5.1 to restore functionality.
```
        temp:
          is_used: true
          entities:
            - sensor.dongle_40_4c_XX_XX_XX_XX_tinner
```
